export interface UseCase {
  sector: string;
  title: string;
  description: string;
  examples: string[];
  source?: string;
}

export const useCases: UseCase[] = [
  {
    sector: "Healthcare",
    title: "AI Diagnostics & Digital Twin Patients",
    description:
      "AI agents analyze medical data to assist diagnosis while digital twins simulate treatment outcomes on virtual patient models before applying them to real patients. The EU's European Virtual Human Twin initiative aims to create personalized health simulations for every citizen.",
    examples: [
      "AI agents triaging radiology scans with 95%+ accuracy",
      "Digital twin organs for surgical planning and drug testing",
      "Personalized treatment plans generated by analyzing genomic data",
    ],
    source: "EU Commission, WHO Digital Health initiatives",
  },
  {
    sector: "Finance",
    title: "Autonomous DeFi Agents & Smart Portfolios",
    description:
      "AI agents managing financial portfolios, executing trades, and optimizing yield across decentralized protocols — all without human intervention. Smart contract-based agents can rebalance, arbitrage, and risk-manage 24/7.",
    examples: [
      "Yield optimization agents moving assets across DeFi protocols",
      "AI-powered risk assessment replacing traditional credit scoring",
      "Autonomous treasury management for DAOs and enterprises",
    ],
    source: "Decrypt, Frontiers in Blockchain",
  },
  {
    sector: "Smart Cities",
    title: "Urban Digital Twins & CitiVerse",
    description:
      "Cities building real-time virtual replicas of their infrastructure to simulate traffic, energy use, emergency response, and urban planning. The EU's CitiVerse project creates immersive urban environments where city planners can test changes before implementing them.",
    examples: [
      "Singapore's Virtual Singapore — a city-scale digital twin",
      "EU's Destination Earth — a planetary digital twin for climate modeling",
      "Traffic optimization through real-time simulation and AI routing",
    ],
    source: "EU Commission CitiVerse, Destination Earth",
  },
  {
    sector: "Enterprise",
    title: "AI Agent Workforce & Autonomous Operations",
    description:
      "Enterprises deploying AI agents to handle procurement, scheduling, logistics, customer service, and internal operations. By 2026, Gartner predicts 40% of enterprise apps will embed AI agents — up from less than 5% in 2025.",
    examples: [
      "AI agents managing supply chain logistics end-to-end",
      "Autonomous procurement agents negotiating vendor contracts",
      "Internal helpdesk agents resolving IT tickets without human involvement",
    ],
    source: "Gartner, Check Point Research",
  },
  {
    sector: "Security",
    title: "The Web 4.0 Threat Landscape",
    description:
      "The convergence of AI, quantum computing, and Web 4.0 creates unprecedented security challenges. AI agents become attack surfaces (prompt injection, data poisoning). Deepfakes erode identity verification. The 'harvest-now, decrypt-later' quantum threat looms. 62% of large organizations experienced third-party compromises in 2025.",
    examples: [
      "Prompt injection attacks turning AI agents into insider threats",
      "AI-generated deepfakes bypassing identity verification",
      "Autonomous malware that adapts its behavior to evade detection",
    ],
    source: "Check Point: The 2026 Tech Tsunami",
  },
  {
    sector: "Creator Economy",
    title: "Autonomous Content & Distribution Agents",
    description:
      "AI agents that create, curate, distribute, and monetize content across platforms autonomously. From generating personalized newsletters to managing social media presence, creative AI agents operate as independent economic actors.",
    examples: [
      "AI agents managing creator social media accounts and engagement",
      "Autonomous content curation and distribution networks",
      "AI-generated music, art, and writing with automated licensing",
    ],
  },
];
